http:
  routers:
    freellmapi:
      rule: "Host(`freellm.aldof.duckdns.org`)"
      service: freellmapi
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    freellmapi:
      loadBalancer:
        servers:
          - url: "http://freellmapi:3001"
