tools_sentries:
  git:
    command: git --version
  node:
    command: node -v
  nvm:
    command: nvm --version
  pnpm:
    command: pnpm -v
  bun:
    command: bun -v
  fvm:
    command: fvm -v
  ollama:
    command: ollama -v
  lmstudio:
    command: lms -v
  fish:
    command: fish -v
  hermes:
    command: hermes -v
  opencode:
    command: opencode -v
  tree:
    command: tree -v
  tailscale:
    command: tailscale -v